# Jekyll configuration

name: pepe的个人博客
description: Welcome

# url is currently only used only for the RSS feed in feed.xml
url: https://494778200pepe.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
## archive: "%b" 只显示英文月份
## categories: "%b-%Y" APR-2018 中文年英文月
date_format: 
  title: "%Y-%m-%d"
  archive: "%Y-%m"
  categories: "%Y-%m"
  tag: "%Y-%m-%d"
# Language
lan: "cn" 
# collections
collections:
  c_collection:


paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
